import Header from "./Header";
import Footer from "./Footer";
import Head from "next/head";

const CommonLayout = ({ children }) => {
  return (
    <div className={"font-[customFont]"}>
      <Head>
        <title>The Weighter</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.ico' />
      </Head>
      <Header />
      <div className='flex flex-col items-center justify-center min-h-screen text-black bg-gray-100 change dark:text-white dark:bg-gray-800'>{children}</div>
      <Footer />
    </div>
  );
};

export default CommonLayout;
